[package]
name = "memorydb"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }